from functools import cached_property

import numpy as np

import autoarray as aa

from autogalaxy.profiles.mass.abstract.abstract import MassProfile
from autogalaxy.profiles.mass.input.input_potential import InputPotential


def gaussian_random_field_from(
    shape_native, pixel_scale: float, power_amplitude: float, power_slope: float, seed: int
) -> np.ndarray:
    """
    A real Gaussian random field realization with isotropic power-law power
    spectrum P(k) = power_amplitude * k^(-power_slope).

    The field is generated by filtering white Gaussian noise in Fourier space
    (multiplying its transform by sqrt(P(k)) and inverse transforming), which
    guarantees a real field whose power spectrum follows P(k); the k = 0 mode
    is zeroed so the field has zero mean. Note this normalization convention
    differs from the ``powerbox`` package used by the original
    implementation — the spectrum's shape and seed-reproducibility are what
    potential-correction validation relies on.

    Parameters
    ----------
    shape_native
        The 2D shape of the realization.
    pixel_scale
        The pixel size, setting the physical frequencies k.
    power_amplitude
        The amplitude of the power spectrum.
    power_slope
        The (positive) slope of the power-law spectrum, P(k) ~ k^-slope.
    seed
        The random seed, making the realization reproducible.
    """
    rng = np.random.default_rng(seed)
    white_noise = rng.normal(size=shape_native)

    ky = np.fft.fftfreq(shape_native[0], d=pixel_scale) * 2.0 * np.pi
    kx = np.fft.fftfreq(shape_native[1], d=pixel_scale) * 2.0 * np.pi
    k_grid = np.sqrt(ky[:, None] ** 2 + kx[None, :] ** 2)

    power = np.zeros_like(k_grid)
    nonzero = k_grid > 0
    power[nonzero] = power_amplitude * k_grid[nonzero] ** (-power_slope)

    field_ft = np.fft.fft2(white_noise) * np.sqrt(power)
    return np.fft.ifft2(field_ft).real


class GaussianRandomField(MassProfile):
    def __init__(
        self,
        mask: aa.Mask2D,
        power_amplitude: float = 1.0,
        power_slope: float = 1.0,
        seed: int = 1,
    ):
        """
        A mass profile whose lensing potential is a Gaussian random field
        realization with power spectrum P(k) = power_amplitude * k^(-power_slope),
        used to simulate extended perturbations of a smooth lens-mass model
        (e.g. for validating potential-correction reconstructions).

        The realization is evaluated on the unmasked pixels of the input mask
        and wrapped in an ``InputPotential``, from which the deflection angles
        and convergence are derived via the mask's sparse derivative
        operators.

        Ported from the ``potential_correction`` package of Cao et al. 2025
        (https://github.com/caoxiaoyue/lensing_potential_correction). If you
        use this profile in your research, please cite Cao et al. 2025;
        citation materials are provided at
        https://github.com/caoxiaoyue/potential_correction_paper. The
        realization here uses a plain-numpy Fourier filter rather than the
        original's ``powerbox`` dependency (see
        ``gaussian_random_field_from``).

        Parameters
        ----------
        mask
            The cleaned 2D mask (an ``aa.Mask2D`` carrying the pixel scale)
            on whose unmasked pixels the potential is defined (see
            ``aa.util.derivative.cleaned_mask_from``).
        power_amplitude
            The amplitude of the potential's power spectrum.
        power_slope
            The (positive) slope of the power-law spectrum, P(k) ~ k^-slope.
        seed
            The random seed, making the realization reproducible.
        """
        self.mask = mask
        self.power_amplitude = power_amplitude
        self.power_slope = power_slope
        self.seed = seed
        super().__init__()

    @cached_property
    def lensing_potential_native(self) -> np.ndarray:
        return gaussian_random_field_from(
            shape_native=self.mask.shape_native,
            pixel_scale=self.mask.pixel_scale,
            power_amplitude=self.power_amplitude,
            power_slope=self.power_slope,
            seed=self.seed,
        )

    @cached_property
    def input_potential(self) -> InputPotential:
        grid = aa.Grid2D.from_mask(mask=self.mask)
        return InputPotential(
            lensing_potential=self.lensing_potential_native[~np.asarray(self.mask)],
            image_plane_grid=np.asarray(grid),
            mask=self.mask,
        )

    def convergence_2d_from(self, grid: aa.type.Grid2DLike, xp=np, **kwargs):
        return self.input_potential.convergence_2d_from(grid=grid, xp=xp, **kwargs)

    def potential_2d_from(self, grid: aa.type.Grid2DLike, xp=np, **kwargs):
        return self.input_potential.potential_2d_from(grid=grid, xp=xp, **kwargs)

    def deflections_yx_2d_from(self, grid: aa.type.Grid2DLike, xp=np, **kwargs):
        return self.input_potential.deflections_yx_2d_from(grid=grid, xp=xp, **kwargs)
